# Generated by Django 2.1 on 2018-10-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitation',
            name='attendance',
            field=models.SmallIntegerField(choices=[(1, '干净'), (2, '比较干净'), (0, '非常干净'), (3, '卫生差')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.SmallIntegerField(choices=[(1, '女'), (0, '男')], default=1),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='attendance',
            field=models.SmallIntegerField(choices=[(4, '请假'), (2, '缺勤'), (1, '迟到'), (3, '早退'), (0, '已签到')], default=0),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(10, 'D'), (30, 'B'), (20, 'C'), (40, 'A'), (0, 'D-')], verbose_name='平时成绩'),
        ),
    ]
