# Generated by Django 2.1 on 2018-10-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitation',
            name='attendance',
            field=models.SmallIntegerField(choices=[(3, '卫生差'), (0, '非常干净'), (2, '比较干净'), (1, '干净')], default=1),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='attendance',
            field=models.SmallIntegerField(choices=[(1, '迟到'), (0, '已签到'), (4, '请假'), (2, '缺勤'), (3, '早退')], default=0),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(0, 'D-'), (10, 'D'), (30, 'B'), (40, 'A'), (20, 'C')], verbose_name='平时成绩'),
        ),
    ]
