# Generated by Django 2.1 on 2018-08-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '角色对应的菜单表',
            },
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': '校区表'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name_plural': '班级表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name_plural': '上课记录表'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '客户信息表'},
        ),
        migrations.AlterModelOptions(
            name='customerfollowup',
            options={'verbose_name_plural': '客户跟进表'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name_plural': '报名表'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': '缴费记录表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='studentrecord',
            options={'verbose_name_plural': '学生学习记录表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '账号表'},
        ),
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.SmallIntegerField(choices=[(0, '面授'), (1, '网络'), (2, '脱产')], verbose_name='班级类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.SmallIntegerField(choices=[(2, '官网'), (5, '知乎'), (4, '51CTO'), (3, '百度推广'), (6, '市场推广'), (0, '转介绍'), (1, 'QQ群')]),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='intention',
            field=models.SmallIntegerField(choices=[(1, '一个月内报名'), (0, '两月内报名'), (3, '不报名'), (2, '已报名')]),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='attendance',
            field=models.SmallIntegerField(choices=[(1, '迟到'), (2, '缺勤'), (0, '已签到'), (3, '早退')], default=0),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(40, 'c+'), (20, 'c-'), (100, 'A+'), (30, 'c'), (70, 'B+'), (80, 'A-'), (50, 'B-'), (90, 'A'), (60, 'B'), (-50, 'D')]),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('customer', 'enrolled_class')},
        ),
        migrations.AlterUniqueTogether(
            name='studentrecord',
            unique_together={('student', 'course_record')},
        ),
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(blank=True, to='crm.Menu', verbose_name='菜单'),
        ),
    ]
