# Generated by Django 2.1 on 2018-08-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180815_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.SmallIntegerField(choices=[(2, '脱产'), (0, '面授'), (1, '网络')], verbose_name='班级类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.SmallIntegerField(choices=[(2, '官网'), (3, '百度推广'), (5, '知乎'), (4, '51CTO'), (0, '转介绍'), (1, 'QQ群'), (6, '市场推广')]),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='intention',
            field=models.SmallIntegerField(choices=[(1, '一个月内报名'), (2, '已报名'), (0, '两月内报名'), (3, '不报名')]),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='attendance',
            field=models.SmallIntegerField(choices=[(3, '早退'), (2, '缺勤'), (1, '迟到'), (0, '已签到')], default=0),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(100, 'A+'), (80, 'A-'), (40, 'c+'), (70, 'B+'), (20, 'c-'), (50, 'B-'), (-50, 'D'), (90, 'A'), (60, 'B'), (30, 'c')]),
        ),
    ]
