# Generated by Django 2.1 on 2018-10-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20181016_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='attendance',
            field=models.SmallIntegerField(choices=[(2, '缺勤'), (1, '迟到'), (0, '已签到'), (3, '早退'), (4, '请假')], default=0),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(40, 'A'), (20, 'C'), (10, 'D'), (0, 'D-'), (30, 'B')], verbose_name='平时成绩'),
        ),
    ]
