# Generated by Django 2.1 on 2018-08-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180816_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.SmallIntegerField(choices=[(0, '面授'), (1, '网络'), (2, '脱产')], verbose_name='班级类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.SmallIntegerField(choices=[(2, '官网'), (3, '百度推广'), (4, '51CTO'), (5, '知乎'), (6, '市场推广'), (1, 'QQ群'), (0, '转介绍')]),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='intention',
            field=models.SmallIntegerField(choices=[(2, '已报名'), (1, '一个月内报名'), (3, '不报名'), (0, '两月内报名')]),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='attendance',
            field=models.SmallIntegerField(choices=[(3, '早退'), (0, '已签到'), (1, '迟到'), (2, '缺勤')], default=0),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(80, 'A-'), (40, 'c+'), (20, 'c-'), (70, 'B+'), (60, 'B'), (50, 'B-'), (100, 'A+'), (90, 'A'), (-50, 'D'), (30, 'c')]),
        ),
    ]
