# Generated by Django 2.1 on 2018-08-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20180816_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.SmallIntegerField(choices=[(0, '面授'), (2, '脱产'), (1, '网络')], verbose_name='班级类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'QQ群'), (0, '转介绍'), (6, '市场推广'), (2, '官网'), (3, '百度推广'), (5, '知乎'), (4, '51CTO')]),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='intention',
            field=models.SmallIntegerField(choices=[(1, '一个月内报名'), (3, '不报名'), (2, '已报名'), (0, '两月内报名')]),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='attendance',
            field=models.SmallIntegerField(choices=[(0, '已签到'), (2, '缺勤'), (3, '早退'), (1, '迟到')], default=0),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(90, 'A'), (50, 'B-'), (40, 'c+'), (60, 'B'), (100, 'A+'), (70, 'B+'), (-50, 'D'), (80, 'A-'), (30, 'c'), (20, 'c-')]),
        ),
    ]
