# Generated by Django 2.1 on 2018-09-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20180816_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='taps',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.SmallIntegerField(choices=[(1, '网络'), (0, '面授'), (2, '脱产')], verbose_name='班级类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.SmallIntegerField(choices=[(0, '转介绍'), (5, '知乎'), (3, '百度推广'), (2, '官网'), (4, '51CTO'), (1, 'QQ群'), (6, '市场推广')]),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='intention',
            field=models.SmallIntegerField(choices=[(3, '不报名'), (0, '两月内报名'), (1, '一个月内报名'), (2, '已报名')]),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='attendance',
            field=models.SmallIntegerField(choices=[(3, '早退'), (2, '缺勤'), (1, '迟到'), (0, '已签到')], default=0),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(100, 'A+'), (90, 'A'), (30, 'c'), (60, 'B'), (70, 'B+'), (40, 'c+'), (50, 'B-'), (20, 'c-'), (80, 'A-'), (-50, 'D')]),
        ),
    ]
